import Layout from "@/components/layout";
import Head from "next/head";
import Image from "next/image";
import vivaImage from "public/Images/Viva.png";
import ocaenImage from "public/Images/Ocean.png";
import ocaenImage_2 from "public/Images/Ocean_2.png";
import webtoonImage from "public/Images/Unreal.PNG";
import previzImage from "public/Images/0223_2.png"
import roadImage from "public/Images/Road.png"



export default  function Projects() {
  return(
    <Layout>
      <Head>
        <title>포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>프로젝트</h1> */}

      <section class="text-gray-600 body-font">

        <div class="container px-5 py-24 mx-auto">
          <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Personal Projects</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table. Franzen you probably haven't heard of them man bun deep jianbing selfies heirloom.</p>
          </div>

          <div class="flex flex-wrap -m-4">

            <div class="lg:w-1/3 sm:w-1/2 p-4">
              <div class="flex relative">
                <Image alt="Images" class="absolute inset-0 w-full h-full object-cover object-center rounded-xl " 
                      src={vivaImage} />
                <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1">Modeling</h2>
                  <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Vivarium</h1>
                  <p class="leading-relaxed">3D rendering in Unreal Engine. Used Quixel Bridge assets and Blender to modeling.</p>
                </div>
              </div>
            </div>

            <div class="lg:w-1/3 sm:w-1/2 p-4">
              <div class="flex relative">
                <Image alt="gallery" class="absolute inset-0 w-full h-full object-cover object-center rounded-xl" src={ocaenImage} / >
                <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1">3D Rendering</h2>
                  <h1 class="title-font text-lg font-medium text-gray-900 mb-3">The Ocean</h1>
                  <p class="leading-relaxed">The Ocean.</p>
                </div>
              </div>
            </div>

            <div class="lg:w-1/3 sm:w-1/2 p-4">
              <div class="flex relative">
                <Image alt="gallery" class="absolute inset-0 w-full h-full object-cover object-center" src={webtoonImage}/ >
                <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1">Webtoon</h2>
                  <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Webtoob BG / Unreal</h1>
                  <p class="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>

            <div class="lg:w-1/3 sm:w-1/2 p-4">
              <div class="flex relative">
                <Image alt="gallery" class="absolute inset-0 w-full h-full object-cover object-center" src={previzImage} />
                <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1">Previz</h2>
                  <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Previz BG / Unreal</h1>
                  <p class="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>

            <div class="lg:w-1/3 sm:w-1/2 p-4">
              <div class="flex relative">
                <Image alt="gallery" class="absolute inset-0 w-full h-full object-cover object-center" src={roadImage} />
                <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1">Level Design</h2>
                  <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Road</h1>
                  <p class="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>

            <div class="lg:w-1/3 sm:w-1/2 p-4">
              <div class="flex relative">
                <Image alt="gallery" class="absolute inset-0 w-full h-full object-cover object-center" src={ocaenImage_2} />
                <div class="px-8 py-10 relative z-10 w-full border-4 border-gray-200 bg-white opacity-0 hover:opacity-100">
                  <h2 class="tracking-widest text-sm title-font font-medium text-indigo-500 mb-1">Ocean</h2>
                  <h1 class="title-font text-lg font-medium text-gray-900 mb-3">Realistic Ocean</h1>
                  <p class="leading-relaxed">Photo booth fam kinfolk cold-pressed sriracha leggings jianbing microdosing tousled waistcoat.</p>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
     
    </Layout>
  );
}